@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "CONFIG_FILE=version_info.txt"
set "CONFIG_FILE_FULL_PATH=%~dp0!CONFIG_FILE!"
set "OUTPUT_FILE=version_info.h"
set "OUTPUT_FILE_FULL_PATH=%~dp0!OUTPUT_FILE!"

if not exist "%CONFIG_FILE_FULL_PATH%" (
    echo Config file not found: "%CONFIG_FILE_FULL_PATH%"
    exit /b 1
)

REM Load config
for /f "usebackq delims= eol=#" %%x in ("%CONFIG_FILE_FULL_PATH%") do (
    set "%%x"
)

set VERSION_PATCH=5
set GIT_HASH=afsr2f32rf
set TAG_DIRTY=dirty

set VERSION=!VERSION_MAJOR!.!VERSION_MINOR!.!VERSION_PATCH!
if defined PRERELEASE_TAG (
    set VERSION=!VERSION!-!PRERELEASE_TAG!
)
if defined TAG_DIRTY (
    set VERSION=!VERSION!-!TAG_DIRTY!
)
set VERSION_INFORMATIONAL=!VERSION!-!GIT_HASH!

(
echo #pragma once
echo.
echo // This is an auto-generated file. Do not edit this file.
echo // To change the version edit the file "!CONFIG_FILE!".
echo // You can set the first two version integers ^(major and minor^) and an optional prerelease tag in the file "!CONFIG_FILE!".
echo // The third version integer ^(patch^) is generated automatically from the number of commits since the file "!CONFIG_FILE!" was edited.
echo // The tag "!TAG_DIRTY!" is added if you have any uncommitted changes when running the version script.
echo.
echo #define VERSION_MINOR %VERSION_MINOR%
echo #define VERSION_MAJOR %VERSION_MAJOR%
echo #define VERSION_PATCH %VERSION_PATCH%
echo #define GIT_HASH "!GIT_HASH!"
echo #define VERSION "!VERSION!"
echo #define VERSION_INFORMATIONAL "!VERSION_INFORMATIONAL!"
) > "%OUTPUT_FILE_FULL_PATH%"

echo Generated %OUTPUT_FILE_FULL_PATH%
endlocal
